import Head from 'next/head'
import styles from '../styles/Home.module.css'
// @ts-ignore
import allData from '../data/all-data.json5'
import {Button} from 'antd'
console.log(allData)
export default function Home() {
  const productList = allData.products.map((product: any) => {
    return (
      <div key={product.model}>
        <h3>{product.model}</h3>
      </div>
    )
  })
    const vendorList = allData.vendors.map((vendor: string) => {
        return (
            <span className={styles.vendorItem} key={vendor}>{vendor}</span>
        )
    })
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          5Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
          {productList}
          <div>{vendorList}</div>
            <Button type="primary" onClick={() => alert(1)}>Primary Button</Button>
      </main>
    </div>
  )
}
